train_ datasets:
    dataroot_noise_train: /scratch3/ven073/datanew/noisetrain
    dataroot_blur_train: /scratch3/ven073/datanew/blurtrain
    dataroot_super_train: /scratch3/ven073/datanew/supertrain
    dataroot_inpaint_train: /scratch3/ven073/datanew/inpaintrain
    dataroot_demask_train: /scratch3/ven073/datanew/masktrain 
val_datasets: 
    dataroot_noise_val: /scratch3/ven073/datanew/noiseval
    dataroot_blur_val: /scratch3/ven073/datanew/blurval
    dataroot_super_val: /scratch3/ven073/datanew/superval
    dataroot_inpaint_val: /scratch3/ven073/datanew/inpaintval
    dataroot_demask_val: /scratch3/ven073/datanew/maskval

